name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"

  hello2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "two"
